FROM ubuntu:latest
RUN apt-get -y update
RUN groupadd -r user && useradd -r -g user user
USER user

# user adding examples
#and container runs only in the specified user it helps to the security threts   